# Generated by Django 5.0.2 on 2024-02-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_dreamdestinationslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamdestinations',
            name='list_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.dreamdestinationslist'),
        ),
    ]
