# Generated by Django 5.0.2 on 2024-02-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_dreamdestinations_list_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DreamDestinations',
            new_name='Destination',
        ),
    ]
