# Generated by Django 5.0.2 on 2024-02-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_rename_dreamdestinations_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.dreamdestinationslist'),
        ),
    ]
