# Generated by Django 5.0.2 on 2024-02-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_alter_dreamdestinationslist_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cities_to_visit', models.IntegerField(default=1)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gui.dreamdestinationslist'),
        ),
    ]
